#!/usr/bin/env bash

function status {
  echo "$(tput bold ; tput setaf 4)$1$(tput sgr0)";
}

status "..Creating Universe.."
git submodule init
git submodule update
for d in */ ; do 
  cd $d;
  git checkout master; 
  git pull; 
  cd ..;
done

status "..BANG!"
