#!/bin/bash

# No need to check for git, brew etc. (can just use HTTP for now, at
# least until package is publicly available)

# will install dependencies locally.
# TODO: for system-wide install pass a `-g`
# by default will install to .bin. TODO can change with --prefix
BINDIR=~/.local/bin
LATEST='http://ndr.md/releases/latest'
DOWNLOADER='curl'
alias curl='curl -s'
mkdir -p $BINDIR

download () {
    # fixme: if this is a subprocess -- will it work?
    command -v curl >/dev/null 2>&1 || 
        { DOWNLOADER='wget'; alias curl='wget -qO- '; }
}

cmd_exists () {
    command -v $1 >/dev/null 2>&1 && 
        echo 'true' ||
        echo 'false';
}

node_version () {
    v=$(node -v | tr -d v | sed 's/\..*$//'); 
    if [ $v -ge '4' ]; then
        echo 'true'
    else
        echo 'false'
    fi
}

node_install () {
    # by default, will install the version I have locally:)
    VERSION='5.3.0'
    PLATFORM=$(uname | tr '[:upper:]' '[:lower:]')

    if [ $PLATFORM = 'darwin' ]; then
        # I don't see any x32 for Darwin!
        ARCH=x64;
    else
        if [ $(uname -m) == 'x86_64' ]; then
            ARCH=x64
        else
            ARCH=x86
        fi
    fi

    PREFIX="$BINDIR/node-v$VERSION-$PLATFORM-$ARCH";
    URL=http://nodejs.org/dist/v$VERSION/node-v$VERSION-$PLATFORM-$ARCH.tar.gz
    echo "Downloading node ($URL) into $BINDIR"
    echo "(this might take a while depending on your connection)"
    mkdir -p $PREFIX;
    curl $URL | tar xzf - --strip-components=1 -C $PREFIX
    mv $PREFIX/bin/* $BINDIR
    rm -rf $PREFIX
    if [[ $PATH != *":$BINDIR"* ]]
    then
        for i in ~/.*shrc; do
            echo "Adding path $PREFIX/bin to startup: $i"
            echo "export PATH=\"$PATH:$BINDIR\" # andromeda node" >> $i
        done
        export PATH="$PATH:$PREFIX/bin"
    fi
}

andromeda_install () {
    # 1 OK, get the code (dev version)
    curl -s $LATEST | tar xzf - --strip-components=1 -C $BINDIR
    ln -sf $BINDIR/andromeda.js $BINDIR/andromeda
}

path_note () {
  echo "You can now launch Andromeda: "
  echo " * if $BINDIR is in your PATH, run \"andromeda\""
  echo " * if not, restart your shell or run \"export PATH=\$PATH:$BINDIR\""
  echo "       (and then run \"andromeda\")"
}

if [[ $(cmd_exists node) == "false" ]]; then
   node_install 
fi

mkdir -p $BINDIR
andromeda_install && path_note || echo 'something went wrong; please let me know.'

